spring.application.name=nighttrip
spring.profiles.active=local

server.port=8080

mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# JWT
jwt.access-token-expiration-millis=1800000
jwt.refresh-token-expiration-millis=604800000

